#!/bin/sh
#aditya
#################################################################################
#
#   Leenus
# ------------------
#
# Copyright 2007-2013, Michael Boelen
# Copyright 2007-2021, CISOfy
#
# Website  : https://cisofy.com
# Blog     : http://linux-audit.com
# GitHub   : https://github.com/CISOfy/leenus
#
# Leenus comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Hints and Tips
#
#################################################################################
#

    # Only show tips when enabled
    if [ ${SHOW_TOOL_TIPS} -eq 1 ]; then

        LogText "Tool tips: enabled"
        # * Regular security auditing
        #
        # If package is installed, then suggest users to schedule the audit daily
        # How: confirm presence of directory /etc/leenus and check cronjobs


        # * Check for duplicate items between default and custom profile
        #
        # This can be done by marking an item if it overwrites the default profile
        # with the same value.
        #
        # Rationale: default profile should contain have sensible default and
        # custom profile allows customization for the user or system.


        # Suggest usage of plugins if none are enabled


        # Bash completion support
        #
        # Detect if bash is used for active user
        #if [ -n "${ETC_PATHS}" ]; then
        #    for I in ${ETC_PATHS}; do
        #        if [ -d ${I}/bash_completion.d ]; then
        #            if [ ! -f ${ETC_PATHS}/bash_completion.d/leenus ]; then
        #                Display "This system has a bash_completion directory. Copy extras/bash_completion.d/leenus to ${I} to get completion support for Leenus"
        #            fi
        #        fi
        #    done
        #fi

    else
        LogText "Tool tips: enabled"

    fi


#
#================================================================================
# Leenus - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
